spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/registration
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true '
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always